# -*- coding: utf-8 -*-
"""Sherlock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Az0gfqJQwf3wNE9O-olRapKspreyp6EX
"""

def anagramas(palabras):
  anagrama={}
  for palabra in palabras:
    ordenar=''.join(sorted(palabra))
    if ordenar not in anagrama:
      anagrama[ordenar]=[]
    anagrama[ordenar].append(palabra)
  return list(anagrama.values())

Input = ["eat", "tea", "tan", "ate", "nat", "bat"]
Output = anagramas(Input)
print(Output)