# -*- coding: utf-8 -*-
"""Valid_Parentheses.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tqvKTOrmKdX3n536yLORVmC_gNL8vSG
"""

def valid(s: str):
    if len(s) >= 1 and len(s) <= 104:
        per = [")", "(", "]", "[", "}", "{"]
        if all(car in per for car in s):
            tb = {")": "(", "]": "[", "}": "{"}
            ver = []
            for le in s:
                if le in tb.values():
                    ver.append(le)
                elif le in tb:
                    if not len(ver) > 0 or ver[-1] != tb[le]:
                        return False, ",Error in the signs"
                    else:
                        ver.pop()
                else:
                    return False, ",Error Unexpected"
            if not ver:
                return True, "Correct"
            else:
                return False, ",Error: unclosed brackets"
        else:
            return False, ",There are letters that are not allowed"
    else:
        return False, ",Size is incorrect"

s = "([])"
res = valid(s)
print(res[0])